// Canonical ingredient → emoji mapping. Used by ingredient chips on the
// confirm screen, ingredient lines on recipe detail, and share card
// templates.
//
// Matching strategy:
//   1. Exact (lowercased, trimmed) lookup in INGREDIENT_EMOJI.
//   2. Longest-substring match against the keys (so "olive oil" wins over
//      "olive", "sweet potato" wins over "potato", etc.).
//   3. Fallback to a generic spoon.
//
// Add new entries here when you spot a common ingredient that's slipping
// through to the default — no other files need to change.

const INGREDIENT_EMOJI = {
  // ── Proteins — poultry / red meat ──────────────────────────────────────
  chicken: "🍗",
  "chicken breast": "🍗",
  "chicken thigh": "🍗",
  "chicken thighs": "🍗",
  "chicken wing": "🍗",
  "chicken wings": "🍗",
  "chicken leg": "🍗",
  "chicken drumstick": "🍗",
  "rotisserie chicken": "🍗",
  "whole chicken": "🍗",
  duck: "🍗",
  turkey: "🦃",
  "ground turkey": "🦃",
  beef: "🥩",
  steak: "🥩",
  "ribeye": "🥩",
  "sirloin": "🥩",
  "flank steak": "🥩",
  "skirt steak": "🥩",
  "filet mignon": "🥩",
  "ground beef": "🥩",
  brisket: "🥩",
  "beef stew": "🥩",
  "stew meat": "🥩",
  pork: "🍖",
  "pork chop": "🍖",
  "pork tenderloin": "🍖",
  "pork shoulder": "🍖",
  "pulled pork": "🍖",
  "ground pork": "🍖",
  lamb: "🍖",
  "lamb chop": "🍖",
  "ground lamb": "🍖",
  ribs: "🍖",
  "short ribs": "🍖",
  "spare ribs": "🍖",
  "baby back ribs": "🍖",
  veal: "🥩",
  venison: "🍖",

  // ── Proteins — cured / processed pork ──────────────────────────────────
  bacon: "🥓",
  ham: "🥓",
  prosciutto: "🥓",
  pancetta: "🥓",
  salami: "🥓",
  pepperoni: "🥓",
  "deli meat": "🥓",
  sausage: "🌭",
  sausages: "🌭",
  chorizo: "🌭",
  bratwurst: "🌭",
  kielbasa: "🌭",
  "hot dog": "🌭",
  "hot dogs": "🌭",
  frankfurter: "🌭",

  // ── Seafood ────────────────────────────────────────────────────────────
  fish: "🐟",
  salmon: "🐟",
  tuna: "🐟",
  cod: "🐟",
  halibut: "🐟",
  trout: "🐟",
  mackerel: "🐟",
  sardine: "🐟",
  sardines: "🐟",
  anchovy: "🐟",
  anchovies: "🐟",
  "sea bass": "🐟",
  tilapia: "🐟",
  snapper: "🐟",
  shrimp: "🍤",
  prawn: "🍤",
  prawns: "🍤",
  lobster: "🦞",
  crab: "🦀",
  "crab meat": "🦀",
  "imitation crab": "🦀",
  scallop: "🦪",
  scallops: "🦪",
  oyster: "🦪",
  oysters: "🦪",
  mussel: "🦪",
  mussels: "🦪",
  clam: "🦪",
  clams: "🦪",
  squid: "🦑",
  calamari: "🦑",
  octopus: "🐙",
  sushi: "🍣",
  sashimi: "🍣",

  // ── Vegan proteins / eggs ──────────────────────────────────────────────
  tofu: "🍱",
  "silken tofu": "🍱",
  "firm tofu": "🍱",
  tempeh: "🍱",
  seitan: "🍱",
  egg: "🥚",
  eggs: "🥚",
  "egg white": "🥚",
  "egg whites": "🥚",
  "egg yolk": "🥚",
  "boiled egg": "🥚",

  // ── Alliums ────────────────────────────────────────────────────────────
  onion: "🧅",
  "red onion": "🧅",
  "white onion": "🧅",
  "yellow onion": "🧅",
  "sweet onion": "🧅",
  shallot: "🧅",
  shallots: "🧅",
  leek: "🧅",
  leeks: "🧅",
  "green onion": "🧅",
  "green onions": "🧅",
  scallion: "🧅",
  scallions: "🧅",
  "spring onion": "🧅",
  chive: "🌿",
  chives: "🌿",
  garlic: "🧄",
  "garlic clove": "🧄",
  "garlic cloves": "🧄",
  "minced garlic": "🧄",

  // ── Vegetables — fruiting / nightshade ────────────────────────────────
  tomato: "🍅",
  tomatoes: "🍅",
  "cherry tomato": "🍅",
  "cherry tomatoes": "🍅",
  "roma tomato": "🍅",
  "grape tomato": "🍅",
  "sun-dried tomato": "🍅",
  "canned tomato": "🍅",
  "tomato sauce": "🍅",
  "tomato paste": "🍅",
  marinara: "🍅",
  ketchup: "🍅",
  "bell pepper": "🫑",
  "bell peppers": "🫑",
  "red pepper": "🫑",
  "green pepper": "🫑",
  "yellow pepper": "🫑",
  "orange pepper": "🫑",
  capsicum: "🫑",
  pepper: "🫑",
  chili: "🌶️",
  chile: "🌶️",
  "chili pepper": "🌶️",
  "chili peppers": "🌶️",
  jalapeño: "🌶️",
  jalapeno: "🌶️",
  habanero: "🌶️",
  serrano: "🌶️",
  poblano: "🌶️",
  cayenne: "🌶️",
  "red pepper flakes": "🌶️",
  "crushed red pepper": "🌶️",
  "chili flakes": "🌶️",
  "chili powder": "🌶️",
  "hot sauce": "🌶️",
  sriracha: "🌶️",
  gochujang: "🌶️",
  harissa: "🌶️",
  "thai chili": "🌶️",
  "anaheim pepper": "🫑",
  tabasco: "🌶️",
  paprika: "🌶️",
  "smoked paprika": "🌶️",
  eggplant: "🍆",
  aubergine: "🍆",

  // ── Vegetables — root ──────────────────────────────────────────────────
  potato: "🥔",
  potatoes: "🥔",
  "russet potato": "🥔",
  "yukon potato": "🥔",
  "baby potato": "🥔",
  "baby potatoes": "🥔",
  "new potato": "🥔",
  "sweet potato": "🍠",
  "sweet potatoes": "🍠",
  yam: "🍠",
  carrot: "🥕",
  carrots: "🥕",
  "baby carrot": "🥕",
  beet: "🥕",
  beets: "🥕",
  beetroot: "🥕",
  radish: "🥕",
  turnip: "🥕",
  parsnip: "🥕",
  rutabaga: "🥕",
  ginger: "🫚",
  "fresh ginger": "🫚",
  "ginger root": "🫚",
  "ground ginger": "🫚",

  // ── Vegetables — cruciferous / other ──────────────────────────────────
  broccoli: "🥦",
  "broccoli florets": "🥦",
  cauliflower: "🥦",
  "brussels sprouts": "🥦",
  cabbage: "🥬",
  "napa cabbage": "🥬",
  "savoy cabbage": "🥬",
  "red cabbage": "🥬",
  "bok choy": "🥬",
  kohlrabi: "🥦",
  corn: "🌽",
  "sweet corn": "🌽",
  "corn on the cob": "🌽",
  "frozen corn": "🌽",
  cornmeal: "🌽",
  polenta: "🌽",

  // ── Vegetables — squash / gourd ───────────────────────────────────────
  cucumber: "🥒",
  cucumbers: "🥒",
  zucchini: "🥒",
  courgette: "🥒",
  "yellow squash": "🥒",
  "summer squash": "🥒",
  pickle: "🥒",
  pickles: "🥒",
  pumpkin: "🎃",
  "butternut squash": "🎃",
  "acorn squash": "🎃",
  "winter squash": "🎃",
  "spaghetti squash": "🎃",

  // ── Vegetables — leafy ────────────────────────────────────────────────
  lettuce: "🥬",
  romaine: "🥬",
  "iceberg lettuce": "🥬",
  "mixed greens": "🥬",
  "salad greens": "🥬",
  "baby greens": "🥬",
  spinach: "🥬",
  "baby spinach": "🥬",
  kale: "🥬",
  "swiss chard": "🥬",
  "collard greens": "🥬",
  arugula: "🥬",
  rocket: "🥬",
  endive: "🥬",
  watercress: "🥬",
  microgreens: "🥬",
  sprouts: "🥬",

  // ── Vegetables — other ────────────────────────────────────────────────
  mushroom: "🍄",
  mushrooms: "🍄",
  "button mushroom": "🍄",
  "button mushrooms": "🍄",
  portobello: "🍄",
  shiitake: "🍄",
  cremini: "🍄",
  "oyster mushroom": "🍄",
  porcini: "🍄",
  truffle: "🍄",
  celery: "🥬",
  asparagus: "🥬",
  artichoke: "🥬",
  fennel: "🥬",
  "green beans": "🫛",
  "string beans": "🫛",
  "snap peas": "🫛",
  "snow peas": "🫛",
  peas: "🫛",
  "frozen peas": "🫛",
  edamame: "🫛",
  okra: "🫛",
  avocado: "🥑",
  guacamole: "🥑",

  // ── Fruits ────────────────────────────────────────────────────────────
  apple: "🍎",
  apples: "🍎",
  "green apple": "🍏",
  "granny smith": "🍏",
  banana: "🍌",
  bananas: "🍌",
  orange: "🍊",
  oranges: "🍊",
  mandarin: "🍊",
  clementine: "🍊",
  tangerine: "🍊",
  lemon: "🍋",
  lemons: "🍋",
  "lemon juice": "🍋",
  "lemon zest": "🍋",
  lime: "🍋",
  limes: "🍋",
  "lime juice": "🍋",
  "lime zest": "🍋",
  pear: "🍐",
  peach: "🍑",
  peaches: "🍑",
  cherry: "🍒",
  cherries: "🍒",
  grape: "🍇",
  grapes: "🍇",
  strawberry: "🍓",
  strawberries: "🍓",
  blueberry: "🫐",
  blueberries: "🫐",
  raspberry: "🫐",
  raspberries: "🫐",
  blackberry: "🫐",
  blackberries: "🫐",
  cranberry: "🫐",
  cranberries: "🫐",
  watermelon: "🍉",
  melon: "🍈",
  cantaloupe: "🍈",
  honeydew: "🍈",
  pineapple: "🍍",
  mango: "🥭",
  papaya: "🥭",
  coconut: "🥥",
  "coconut milk": "🥥",
  "coconut cream": "🥥",
  "coconut oil": "🥥",
  "shredded coconut": "🥥",
  kiwi: "🥝",
  fig: "🍐",
  figs: "🍐",
  pomegranate: "🍎",
  date: "🥥",
  dates: "🥥",
  raisin: "🍇",
  raisins: "🍇",
  prune: "🍇",
  prunes: "🍇",

  // ── Grains / starches ──────────────────────────────────────────────────
  rice: "🍚",
  "white rice": "🍚",
  "brown rice": "🍚",
  basmati: "🍚",
  jasmine: "🍚",
  "jasmine rice": "🍚",
  "arborio rice": "🍚",
  "wild rice": "🍚",
  "sushi rice": "🍣",
  "rice noodle": "🍜",
  pasta: "🍝",
  spaghetti: "🍝",
  fettuccine: "🍝",
  linguine: "🍝",
  penne: "🍝",
  rigatoni: "🍝",
  ziti: "🍝",
  bowtie: "🍝",
  farfalle: "🍝",
  macaroni: "🍝",
  orzo: "🍝",
  rotini: "🍝",
  lasagna: "🍝",
  ravioli: "🍝",
  tortellini: "🍝",
  gnocchi: "🍝",
  noodle: "🍜",
  noodles: "🍜",
  ramen: "🍜",
  udon: "🍜",
  soba: "🍜",
  vermicelli: "🍜",
  "egg noodle": "🍜",
  "egg noodles": "🍜",
  bread: "🍞",
  "white bread": "🍞",
  "wheat bread": "🍞",
  "whole wheat bread": "🍞",
  sourdough: "🍞",
  rye: "🍞",
  toast: "🍞",
  breadcrumbs: "🍞",
  "panko": "🍞",
  baguette: "🥖",
  ciabatta: "🥖",
  focaccia: "🥖",
  croissant: "🥐",
  bagel: "🥯",
  tortilla: "🌯",
  tortillas: "🌯",
  wrap: "🌯",
  wraps: "🌯",
  "flour tortilla": "🌯",
  "corn tortilla": "🌽",
  pita: "🥙",
  naan: "🥙",
  flatbread: "🥙",
  pancake: "🥞",
  pancakes: "🥞",
  waffle: "🧇",
  waffles: "🧇",
  quinoa: "🌾",
  couscous: "🌾",
  barley: "🌾",
  farro: "🌾",
  bulgur: "🌾",
  millet: "🌾",
  oats: "🌾",
  oatmeal: "🌾",
  "rolled oats": "🌾",
  "steel cut oats": "🌾",
  flour: "🌾",
  "all-purpose flour": "🌾",
  "bread flour": "🌾",
  "almond flour": "🥜",
  "coconut flour": "🥥",
  "whole wheat flour": "🌾",
  cornstarch: "🌾",
  cereal: "🥣",
  granola: "🥣",
  muesli: "🥣",

  // ── Dairy ──────────────────────────────────────────────────────────────
  milk: "🥛",
  "whole milk": "🥛",
  "skim milk": "🥛",
  "2% milk": "🥛",
  "almond milk": "🥛",
  "soy milk": "🥛",
  "oat milk": "🥛",
  buttermilk: "🥛",
  cream: "🥛",
  "heavy cream": "🥛",
  "whipping cream": "🥛",
  "half and half": "🥛",
  "sour cream": "🥛",
  "crème fraîche": "🥛",
  yogurt: "🥛",
  "greek yogurt": "🥛",
  butter: "🧈",
  "unsalted butter": "🧈",
  "salted butter": "🧈",
  ghee: "🧈",
  cheese: "🧀",
  cheddar: "🧀",
  "sharp cheddar": "🧀",
  mozzarella: "🧀",
  "fresh mozzarella": "🧀",
  parmesan: "🧀",
  parmigiano: "🧀",
  pecorino: "🧀",
  feta: "🧀",
  "goat cheese": "🧀",
  brie: "🧀",
  camembert: "🧀",
  gouda: "🧀",
  swiss: "🧀",
  "swiss cheese": "🧀",
  "blue cheese": "🧀",
  gorgonzola: "🧀",
  "cream cheese": "🧀",
  ricotta: "🧀",
  "cottage cheese": "🧀",
  provolone: "🧀",
  "monterey jack": "🧀",
  "pepper jack": "🧀",
  manchego: "🧀",
  halloumi: "🧀",
  paneer: "🧀",

  // ── Condiments / sauces / vinegars ────────────────────────────────────
  "soy sauce": "🫙",
  tamari: "🫙",
  vinegar: "🫙",
  balsamic: "🫙",
  "balsamic vinegar": "🫙",
  "apple cider vinegar": "🫙",
  "rice vinegar": "🫙",
  "white vinegar": "🫙",
  "red wine vinegar": "🫙",
  mustard: "🫙",
  dijon: "🫙",
  "dijon mustard": "🫙",
  "yellow mustard": "🫙",
  "whole grain mustard": "🫙",
  mayo: "🫙",
  mayonnaise: "🫙",
  worcestershire: "🫙",
  "fish sauce": "🫙",
  "oyster sauce": "🫙",
  "hoisin sauce": "🫙",
  "teriyaki sauce": "🫙",
  "bbq sauce": "🫙",
  "barbecue sauce": "🫙",
  salsa: "🌶️",
  hummus: "🫘",
  tahini: "🫘",
  pesto: "🌿",
  miso: "🫘",
  "pasta sauce": "🍅",
  "alfredo sauce": "🥛",
  "ranch dressing": "🥛",
  vinaigrette: "🫙",

  // ── Stocks / broths ────────────────────────────────────────────────────
  broth: "🥣",
  stock: "🥣",
  "chicken broth": "🥣",
  "beef broth": "🥣",
  "vegetable broth": "🥣",
  "chicken stock": "🥣",
  "beef stock": "🥣",
  "vegetable stock": "🥣",
  "bone broth": "🥣",
  bouillon: "🥣",

  // ── Oils / fats ───────────────────────────────────────────────────────
  "olive oil": "🫒",
  "extra virgin olive oil": "🫒",
  olive: "🫒",
  olives: "🫒",
  "kalamata olive": "🫒",
  "vegetable oil": "🫗",
  "canola oil": "🫗",
  "sunflower oil": "🫗",
  "corn oil": "🫗",
  "peanut oil": "🥜",
  "sesame oil": "🫗",
  "avocado oil": "🥑",
  oil: "🫗",
  lard: "🧈",
  shortening: "🧈",

  // ── Herbs ──────────────────────────────────────────────────────────────
  basil: "🌿",
  "fresh basil": "🌿",
  "thai basil": "🌿",
  parsley: "🌿",
  "italian parsley": "🌿",
  "flat-leaf parsley": "🌿",
  cilantro: "🌿",
  "fresh cilantro": "🌿",
  coriander: "🌿",
  dill: "🌿",
  "fresh dill": "🌿",
  thyme: "🌿",
  "fresh thyme": "🌿",
  rosemary: "🌿",
  "fresh rosemary": "🌿",
  oregano: "🌿",
  mint: "🌿",
  "fresh mint": "🌿",
  peppermint: "🌿",
  spearmint: "🌿",
  sage: "🌿",
  tarragon: "🌿",
  "bay leaf": "🌿",
  "bay leaves": "🌿",
  "lemon grass": "🌿",
  lemongrass: "🌿",
  "kaffir lime leaf": "🌿",

  // ── Spices / seasonings ──────────────────────────────────────────────
  salt: "🧂",
  "sea salt": "🧂",
  "kosher salt": "🧂",
  "table salt": "🧂",
  "black pepper": "🧂",
  "white pepper": "🧂",
  peppercorn: "🧂",
  peppercorns: "🧂",
  "ground pepper": "🧂",
  cumin: "🧂",
  "ground cumin": "🧂",
  turmeric: "🧂",
  cinnamon: "🧂",
  "cinnamon stick": "🧂",
  nutmeg: "🧂",
  cloves: "🧂",
  cardamom: "🧂",
  "garlic powder": "🧂",
  "onion powder": "🧂",
  "curry powder": "🍛",
  "garam masala": "🍛",
  "five spice": "🧂",
  "italian seasoning": "🌿",
  "herbes de provence": "🌿",
  "old bay": "🧂",
  "everything bagel seasoning": "🧂",
  vanilla: "🍦",
  "vanilla extract": "🍦",
  "vanilla bean": "🍦",
  "almond extract": "🥜",

  // ── Nuts / seeds ─────────────────────────────────────────────────────
  almond: "🥜",
  almonds: "🥜",
  "sliced almonds": "🥜",
  walnut: "🥜",
  walnuts: "🥜",
  peanut: "🥜",
  peanuts: "🥜",
  "peanut butter": "🥜",
  "almond butter": "🥜",
  "nut butter": "🥜",
  pecan: "🥜",
  pecans: "🥜",
  cashew: "🥜",
  cashews: "🥜",
  pistachio: "🥜",
  pistachios: "🥜",
  hazelnut: "🥜",
  hazelnuts: "🥜",
  "pine nut": "🥜",
  "pine nuts": "🥜",
  "macadamia nut": "🥜",
  "brazil nut": "🥜",
  sesame: "🌾",
  "sesame seed": "🌾",
  "sesame seeds": "🌾",
  "sunflower seed": "🌻",
  "sunflower seeds": "🌻",
  "pumpkin seed": "🎃",
  "pumpkin seeds": "🎃",
  pepita: "🎃",
  pepitas: "🎃",
  "chia seed": "🌾",
  "chia seeds": "🌾",
  "flax seed": "🌾",
  "flax seeds": "🌾",
  "poppy seed": "🌾",
  "poppy seeds": "🌾",
  "hemp seed": "🌾",

  // ── Beans / legumes ──────────────────────────────────────────────────
  bean: "🫘",
  beans: "🫘",
  "black bean": "🫘",
  "black beans": "🫘",
  "kidney bean": "🫘",
  "kidney beans": "🫘",
  "pinto bean": "🫘",
  "pinto beans": "🫘",
  "white bean": "🫘",
  "white beans": "🫘",
  "navy bean": "🫘",
  "cannellini": "🫘",
  garbanzo: "🫘",
  "garbanzo bean": "🫘",
  chickpea: "🫘",
  chickpeas: "🫘",
  "fava bean": "🫘",
  "lima bean": "🫘",
  "refried bean": "🫘",
  lentil: "🫘",
  lentils: "🫘",
  "red lentil": "🫘",
  "green lentil": "🫘",
  "brown lentil": "🫘",

  // ── Sweeteners / baking ──────────────────────────────────────────────
  sugar: "🍯",
  "white sugar": "🍯",
  "brown sugar": "🍯",
  "powdered sugar": "🍯",
  "confectioners sugar": "🍯",
  "coconut sugar": "🍯",
  honey: "🍯",
  "maple syrup": "🍯",
  syrup: "🍯",
  molasses: "🍯",
  agave: "🍯",
  jam: "🍯",
  jelly: "🍯",
  preserves: "🍯",
  marmalade: "🍯",
  chocolate: "🍫",
  "dark chocolate": "🍫",
  "milk chocolate": "🍫",
  "white chocolate": "🍫",
  "chocolate chip": "🍫",
  "chocolate chips": "🍫",
  cocoa: "🍫",
  "cocoa powder": "🍫",
  nutella: "🍫",
  "baking powder": "🧂",
  "baking soda": "🧂",
  yeast: "🌾",
  "active dry yeast": "🌾",
  "instant yeast": "🌾",
  gelatin: "🍮",

  // ── Beverages / alcohol ──────────────────────────────────────────────
  water: "💧",
  "ice water": "💧",
  wine: "🍷",
  "red wine": "🍷",
  "white wine": "🍷",
  "rosé": "🍷",
  "rose wine": "🍷",
  champagne: "🍾",
  prosecco: "🍾",
  beer: "🍺",
  lager: "🍺",
  ale: "🍺",
  stout: "🍺",
  cider: "🍎",
  "hard cider": "🍎",
  rum: "🥃",
  whiskey: "🥃",
  bourbon: "🥃",
  vodka: "🥃",
  gin: "🥃",
  tequila: "🥃",
  brandy: "🥃",
  sake: "🍶",
  mirin: "🍶",
  "rice wine": "🍶",
  coffee: "☕",
  espresso: "☕",
  "instant coffee": "☕",
  tea: "🍵",
  "green tea": "🍵",
  "black tea": "🍵",
  juice: "🧃",
  "orange juice": "🧃",
  "apple juice": "🧃",
  "cranberry juice": "🧃",
  lemonade: "🧃",
  "iced tea": "🧃",
  smoothie: "🥤",
  soda: "🥤",
  cola: "🥤",
  "club soda": "🥤",
  "sparkling water": "🥤",
  seltzer: "🥤",
  "ginger ale": "🥤",
  "pinot grigio": "🍷",
  "pinot noir": "🍷",
  chardonnay: "🍷",
  sauvignon: "🍷",
  cabernet: "🍷",
  merlot: "🍷",

  // ── Prepared / dish-style ingredients (used when a recipe lists a
  // ready-made component as an input — pizza dough, taco shells, etc.)
  pizza: "🍕",
  "pizza dough": "🍕",
  "pizza crust": "🍕",
  taco: "🌮",
  "taco shell": "🌮",
  "taco shells": "🌮",
  burrito: "🌯",
  burger: "🍔",
  "burger patty": "🍔",
  "veggie burger": "🍔",
  salad: "🥗",
  "salad mix": "🥗",
  omelet: "🍳",
  omelette: "🍳",
  frittata: "🍳",
  quiche: "🥧",
  sandwich: "🥪",
  "grilled cheese": "🥪",
  blt: "🥪",
  panini: "🥪",
};

const DEFAULT_EMOJI = "🍴";

// Modifiers stripped before lookup so "fresh basil", "extra virgin olive
// oil", "frozen broccoli", "ground cumin", "diced tomatoes" all reduce
// to the core ingredient before matching. Order matters only insofar as
// we strip the longer phrases first via a single regex.
const STRIP_MODIFIERS = [
  "extra virgin", "extra-virgin", "boneless skinless", "wild caught",
  "wild-caught", "free range", "free-range", "low fat", "low-fat",
  "non fat", "non-fat", "fat free", "fat-free", "low sodium",
  "low-sodium", "no salt added",
  "fresh", "dried", "frozen", "organic", "raw", "cooked", "ground",
  "whole", "chopped", "minced", "sliced", "diced", "shredded",
  "grated", "ripe", "unripe", "overripe", "boneless", "skinless",
  "lean", "extra", "virgin", "large", "small", "medium", "baby",
  "wild", "smoked", "roasted",
];
const MOD_REGEX = new RegExp(
  `\\b(${STRIP_MODIFIERS.map((m) => m.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")).join("|")})\\b`,
  "gi",
);

// Category fallbacks — used when no specific entry matches but we can
// still guess the category from a stem word. Keeps generic ingredients
// like "venison" or "monkfish" looking like food rather than a spoon.
const PRODUCE_HINTS = ["vegetable", "veggie", "greens", "fruit"];
const MEAT_HINTS = ["meat", "loin", "shank", "chop", "roast", "cutlet"];
const SEAFOOD_HINTS = ["fish", "fillet", "seafood", "shellfish", "roe"];
const DAIRY_HINTS = ["cheese", "milk", "cream", "yogurt", "dairy"];
const GRAIN_HINTS = ["grain", "flour", "bread", "cereal"];
const HERB_HINTS = ["herb", "leaves", "leaf"];
const SPICE_HINTS = ["spice", "seasoning", "powder"];
const OIL_HINTS = ["oil", "vinegar"];
const BEVERAGE_HINTS = ["drink", "juice", "soda", "wine", "beer", "tea", "coffee"];
const NUT_HINTS = ["nut", "nuts", "seed", "seeds"];

// Sort keys longest-first so substring matching prefers the most specific
// entry (e.g. "olive oil" matches before plain "olive", "sweet potato"
// before "potato", "garlic powder" before "garlic"). Computed once at
// module load; cheap.
const SORTED_KEYS = Object.keys(INGREDIENT_EMOJI).sort(
  (a, b) => b.length - a.length,
);

/**
 * Look up the best food emoji for a given ingredient name.
 *
 * Strategy:
 *   1. Exact lookup on the raw lowercased name.
 *   2. Strip common modifiers (fresh / dried / extra virgin / boneless …)
 *      and try the exact lookup again.
 *   3. Longest-substring match against the dictionary.
 *   4. Category fallback: if the name contains a category hint word
 *      ("fish fillet", "vegetable broth"), use that bucket's emoji.
 *   5. Generic fallback (🍴).
 */
export function getEmojiForIngredient(name) {
  if (!name) return DEFAULT_EMOJI;
  const raw = String(name).toLowerCase().trim();
  if (!raw) return DEFAULT_EMOJI;

  // 1. Exact match on the raw name.
  if (INGREDIENT_EMOJI[raw]) return INGREDIENT_EMOJI[raw];

  // 2. Strip modifiers, collapse whitespace, try exact again.
  const stripped = raw.replace(MOD_REGEX, " ").replace(/\s+/g, " ").trim();
  if (stripped && stripped !== raw && INGREDIENT_EMOJI[stripped]) {
    return INGREDIENT_EMOJI[stripped];
  }

  // 3. Longest-substring lookup against the original (which preserves
  // multi-word entries like "olive oil") and then against the stripped
  // form (which catches "sweet potato" inside "roasted sweet potatoes").
  for (const key of SORTED_KEYS) {
    if (raw.includes(key)) return INGREDIENT_EMOJI[key];
  }
  if (stripped) {
    for (const key of SORTED_KEYS) {
      if (stripped.includes(key)) return INGREDIENT_EMOJI[key];
    }
  }

  // 4. Category hint fallback. Pick the bucket whose hint word appears
  // in the cleaned name. Checked in approximate specificity order.
  const test = stripped || raw;
  if (hasHint(test, SEAFOOD_HINTS)) return "🐟";
  if (hasHint(test, MEAT_HINTS)) return "🥩";
  if (hasHint(test, DAIRY_HINTS)) return "🥛";
  if (hasHint(test, NUT_HINTS)) return "🥜";
  if (hasHint(test, HERB_HINTS)) return "🌿";
  if (hasHint(test, SPICE_HINTS)) return "🧂";
  if (hasHint(test, OIL_HINTS)) return "🫒";
  if (hasHint(test, BEVERAGE_HINTS)) return "🥤";
  if (hasHint(test, GRAIN_HINTS)) return "🌾";
  if (hasHint(test, PRODUCE_HINTS)) return "🥕";

  // 5. Generic food.
  return DEFAULT_EMOJI;
}

function hasHint(name, hints) {
  for (const h of hints) {
    if (new RegExp(`\\b${h}\\b`).test(name)) return true;
  }
  return false;
}

// Legacy name — kept so existing imports keep working. Prefer
// `getEmojiForIngredient` in new code.
export const emojiForIngredient = getEmojiForIngredient;
